app:
  number_of_threads: 8
  run_as_daemon: false
  log:
    log_path: ../logs
    logfile_base_name: myapp
    log_size_limit: 100000000  # 100MB
    max_files: 10
    log_level: DEBUG
    display_local_time: true  # 使用本地时间而非UTC
listeners:
  - address: "0.0.0.0"
    port: 80
    https: false